### ISSUE TITLE
EROR

### ISSUE THREAD

**Issue by ensofter** [synw/django-userprofiles2#1]
This command does not exist - git install git+https://github.com/synw/django-userprofiles.git

I downloaded all your userprofiles folder and threw it into my project.

I have errror - No module named 'braces'

Ok. Im install django-braces and have 5 ERRROR.

What i do incorrect?

**Comment by synw** [comment]
Thanks for signaling it: this module has not been updated since a while. I'll check this out and update as soon as possible.

I should build a pip release by the way.

**Comment by synw** [comment]
Ok I checked it out: the module is working and was updated for Django 1.11 before. It was the install doc that was very incomplete.

I tried to make a pip release but it appears that the name is already taken by a dead project (last update 5 years ago). I guess we will have to change the name. Any suggestions?

Let me know if it works for you now.
