### ISSUE TITLE
email verification not working

### ISSUE THREAD

**Issue by Lifechess** [synw/django-userprofiles2#3]
completion level only work for personnel info and not work for email verification
note that i try to use it on django 2.0

**Comment by synw** [comment]
It used to work. Unfortunately I have no time to investigate this now, sorry. The module should also be upgraded for Django 2 one of these days. I'll have a look when I can

**Comment by synw** [comment]
The module was upgraded for Django 2 and I verified the completion percentage for email verification: it works
