### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by Gittinhub** [synw/django-userprofiles2#4]
Could someone provide the step-by-step commands to install ?
Cloning this archive and using the commands said in home page does not provide the complete application.

**Comment by synw** [comment]
Hi. This package has not been updated for a long time, I guess this is why it does not work well. What version of Django do you use?
I need to upgrade it and change the name to make a pip release (this name is taken by a dead project on pypi). The templates are made with the obsolete Bootstrap 3, this will need a serious update as well. I would use help for the templates if anyone wishes to help.
I'll try to find the time for an upgrade as several people asked in issues

**Comment by Gittinhub** [comment]
Hi and thanks for your reply.

django.VERSION
(2, 1, 3, 'final', 0)

I don't know much about the project cause i did not see it running but seems almost every django application need it as it is a starting point. 
I thought that creating a virtualenv directory and running the pip command line should generate a complete application. So after that, just> manage.py runserver  and it is up!
I think if it provide this fast start for django projects it will reach millions of downloads.

**Comment by synw** [comment]
I updated the module to work with Django 2 and removed some no longer needed dependencies by the way. 

The templates are still the old Bootstrap 3 ones and there is work to do here to get decent default templates. Any help would be appreciated. I plan to make a templates set using Bulma css but not for Bootstrap 4 that I don't use. I'll make an option to be able to select templates sets so if anyone is interested in providing templates for any css framework they can be added. A css framework is useful because of components like progress bar, but it still can be made in vanilla css.

The module was renamed to be able to deliver a pip version once we will have good templates.

**Comment by Gittinhub** [comment]
I would like i could help, but i am a beginner and i don't have time too.

I still don't understand django framework completely, but after your fixes, a pip commend would be sufficient to provide a complete installation and then > manage.py runserver.

I am asking this cause after downloading your project, there was no settings.py file to configure, so i could not proceed since all files needed wasn't there.

**Comment by synw** [comment]
> after downloading your project, there was no settings.py file

This is just a Django module, not a complete project. You need to start a project by yourself (`django-admin startproject myproject`): this will get you a settings file and everything. Then install the module

I suggest you read more doc and do the tutorial to get a better understanding on how things work in a Django project

**Comment by Gittinhub** [comment]
Ok, i understand... but...

Then install the module

Your command line did not mention userprofiles2: pip install django-allauth django-avatar

Shouldn't the command line include it like this:

pip install django-allauth django-avatar django-userprofiles2

**Comment by synw** [comment]
It will but there is no pip release yet. After the pip line do `git clone https://github.com/synw/django-userprofiles2.git` and move the `userprofiles2` folder to your Django project

**Comment by Gittinhub** [comment]
Still can't get it up.

ModuleNotFoundError: No module named 'userprofiles'

Also, had to include the line in urls.py: 
from django.conf.urls import include

Seems that somewhere in your code the name of the module is still "userprofiles"

**Comment by Gittinhub** [comment]
Also i had to add 'django-userprofiles2' to settings, not 'userprofiles2'

**Comment by Gittinhub** [comment]
I found that the error ModuleNotFoundError: No module named 'userprofiles' is related to the urls.py file

specially this line: path(r'^profile/', include('django-userprofiles2.urls')),

Note that i changed it to everything 'userprofiles2', 'userprofiles', and still get the same error

**Comment by synw** [comment]
I updated the readme for the Django 2 urls syntax:

`path('profile/', include('userprofiles2.urls')),`

**Comment by Gittinhub** [comment]
It does not resolve the problem

**Comment by synw** [comment]
Paste the stack trace here so we can check what is the problem. The module is working for me

**Comment by Gittinhub** [comment]
ModuleNotFoundError: No module named 'django-userprofiles2.urls'

That's the problem... 

But i changed as i said to everything... 'userprofiles2.urls'  and 'userprofiles.urls'

**Comment by Gittinhub** [comment]
Here are the commands executed and then the changes already discussed... If you did something different after that commands please tell.

mkdir UserProfiles2Env
virtualenv UserProfiles2Env/
source UserProfiles2Env/bin/activate
pip3 install django-allauth django-avatar
django-admin startproject UserProfiles2Source
git clone https://github.com/synw/django-userprofiles2.git
mv django-userprofiles2 UserProfiles2Source/

**Comment by synw** [comment]
`mv django-userprofiles2/userprofiles2 UserProfiles2Source/`

**Comment by Gittinhub** [comment]
OK. Thanks. I finally could get it UP!

But after upload a new avatar picture i get:

"POST /avatar/add/ HTTP/1.1" 302 0
[25/Nov/2018 15:37:48] "GET /avatar/change/ HTTP/1.1" 200 1257
Not Found: /avatar/change/avatars/myusername/resized/80/avatarpicture.jpg
[25/Nov/2018 15:37:48] "GET /avatar/change/avatars/myusername/resized/80/avatarpicture.jpg HTTP/1.1" 404 3118

Any idea?

**Comment by synw** [comment]
Could you please open a new issue for this problem? I'll investigate this as soon as I'll have a bit of time
