### ISSUE TITLE
Not Found Resized picture after upload

### ISSUE THREAD

**Issue by Gittinhub** [synw/django-userprofiles2#5]
After upload a new avatar picture i get:

"POST /avatar/add/ HTTP/1.1" 302 0
[25/Nov/2018 15:37:48] "GET /avatar/change/ HTTP/1.1" 200 1257
Not Found: /avatar/change/avatars/myusername/resized/80/avatarpicture.jpg
[25/Nov/2018 15:37:48] "GET /avatar/change/avatars/myusername/resized/80/avatarpicture.jpg HTTP/1.1" 404 3118

Any idea?

**Comment by synw** [comment]
I did not have time to test it yet but at first look it is an url problem and this might be related to the django-avatar [AVATAR_STORAGE_DIR](https://django-avatar.readthedocs.io/en/latest/#AVATAR_STORAGE_DIR) setting. According to the Django standards the thumbnail is supposed to be pulled from somewhere in `/media`

**Comment by Gittinhub** [comment]
Ok. Thanks. 

Unsuccessfully did some searches but could not found the solution. Will be waiting.

**Comment by synw** [comment]
I've just tested: it works for me. Did you set your `MEDIA_URL` in settings?

**Comment by Gittinhub** [comment]
yes, it's working now!
Thanks.

I added the necessary configuration after some searches.

But let me ask you something...

You know that in admin area, we can click and edit the avatar images right? We can upload, see and delete.
Why not use the already done CRUD page our projects? Is there a way? 
Of course if we copy the files somehow but i am asking a clean and easy way, so woudn't be necessary to do a new crud for it... is there  way?

**Comment by synw** [comment]
I don't understand your point, but all that is related to the avatars relies on django-avatar and this module just leverages it

**Comment by Gittinhub** [comment]
Every django package comes with a CRUD in the admin area, right? 
Why not use that CRUD already done in the admin area inside the system we build instead of build a new CRUD with the package! Got?
